[GLOBAL]
pants_version = "2.16.0rc1"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.autoflake",
  "pants.backend.python.lint.pyupgrade",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.bandit",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.build_files.fmt.black",
  "pants.backend.build_files.fix.deprecations",
]

[anonymous-telemetry]
enabled = true
repo_id = "E3086EEB-222E-4AAF-8EE5-B797EB7C3B16"

[python]
interpreter_constraints = ["==3.10.*"]
enable_resolves = true
tailor_ignore_empty_init_files = false
default_resolve = "python-default"
pip_version = "23.0.1"

[python-infer]
init_files = "always"
unowned_dependency_behavior = "error"

[python-repos]
indexes.add = [
  "https://download.pytorch.org/whl/cpu",
  "https://download.pytorch.org/whl/cu118",
]

[python.resolves]
python-default = "3rdparty/python-lock.txt"
cpu = "3rdparty/python-cpu-lock.txt"
gpu = "3rdparty/python-gpu-lock.txt"

[python.resolves_to_interpreter_constraints]
python-default = ["==3.10.*"]
cpu = ["==3.10.*"]
gpu = ["==3.10.*"]

[source]
marker_filenames = ["pyproject.toml"]
